version: '3.9'

services:
  frontend:
    build: ./frontend
    container_name: react_app
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: node_api
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: mongodb://mongo:27017/mydatabase
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: mydatabase

volumes:
  mongo_data:
